### ISSUE TITLE
깃헙의 프로필 이미지 최신화 요청

### ISSUE THREAD

**Issue by hcg-jade-min** [jiwoon-jung-hcg/hcsg-front#5]
슬랙에서 유저를 확인할 때 유저의 이름뿐만 아니라 프로필 이미지를 통해 누군지 바로 확인이 가능합니다.
현재 새로 입사하신 분들이 5명인데 5분의 프로필이 깃헙 default 프로필이라 헷갈릴 수 있기 때문에 깃헙의 프로필 이미지도 최신화시켜주세요.

가능하다면 슬랙에서 설정하신 프로필 이미지로 통일시켜 깃헙 프로필 이미지를 설정하시는 것이 좋을 것 같습니다.
왜냐하면 슬랙에서 매일 보는 이미지를 깃헙에서 보기만 해도 `jiwoon-jung-hcg` 을 확인하지 않고도 다른 분들이 바로 직관적으로 지운님이라는 걸 알 수 있기 때문입니다.

퇴근 전에 이번에 입사하신 분들 깃헙 한 번 둘러봤는데 프론트 분들 중에 지운님의 레포만 public 이라 제가 접근할 수 있어서 해당 내용 남깁니다.
내일 출근하시게 되면 우성님과 하늘님에게도 해당 내용 공유하여 3분 모두 깃헙 프로필 이미지 최신화할 수 있도록 해주세요.

**Comment by jiwoon-jung-hcg** [comment]
인지를 못하고 있었습니다.
피드백 주셔서감사합니다 !
내용은 두분께 전달드렸습니다 :)
